name = "Fabricated Adventures 26"
author = "AgentK"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d059a5f4d017f953f45bcd9ee7cfe48bebbfd79309040e7d6b8c212296d55ae4"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
