name = "Fabricated Adventures 26"
author = "AgentK"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1fb47f06a83895047eb9c9fa15bda06a2c074bb02a2138fb46c4e1259bb8d98"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
