name = "Fabricated Adventures 26"
author = "AgentK"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfd5762b21d7a4bcb89121c0e62c6149be9ec09de43bc957cff27cb9f3d384a5"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
